Offlinebans
nekodevone/nwapi-plugins pull request #3
Opened 2023-01-21 12:13 UTC by Skarpelen

### Список изменений:

Добавлен функционирующий офбан

### Чек-лист:

- [ ] Работы окончены, PR готов к рассмотрению
- [ ] Проект собирается без ошибок

2023-01-21 13:30 UTC, JasKill requested changes
Пока исправь это

2023-01-21 13:30 UTC, JasKill commented on src/Padoru.OfflineBans/Padoru.OfflineBans.csproj
> +	</ItemGroup>
Эти зависимости не нужны

2023-01-21 13:30 UTC, JasKill commented on src/Padoru.OfflineBans/Commands/RecieverParent.cs
> +    using System;
Перемести выше namespace

2023-01-21 13:30 UTC, JasKill commented on src/Padoru.OfflineBans/Commands/Modify.cs
> +    using System.Linq;
Перемести выше namespace

2023-01-21 13:30 UTC, JasKill commented on src/Padoru.OfflineBans/Commands/Delete.cs
> +    using System.Linq;
Перемести выше namespace

2023-01-21 13:30 UTC, JasKill commented on src/Padoru.OfflineBans/Commands/Add.cs
> +    using System.Linq;
Перемести выше namespace

2023-01-21 13:30 UTC, JasKill commented on src/Padoru.OfflineBans/Classes/WantedUser.cs
> +    using PlayerAPI = PluginAPI.Core.Player;
Перемести выше namespace

2023-01-21 13:30 UTC, JasKill commented on src/Padoru.OfflineBans/Classes/Tools.cs
> +    using System.Text.RegularExpressions;
Перемести выше namespace

2023-01-21 13:30 UTC, JasKill commented on src/Padoru.OfflineBans/Commands/Modify.cs
> +    [CommandHandler(typeof(GameConsoleCommandHandler))]
В твоем случае только RecieverParent должен иметь эти атрибуты

2023-01-21 13:30 UTC, JasKill commented on src/Padoru.OfflineBans/Classes/Tools.cs
> +        public static string filepath { get; } = Paths.PluginAPI + dirname;
Это не должно не `filepath`, а `FolderPath`. Это же папка, а не файл

2023-01-21 13:30 UTC, JasKill commented on src/Padoru.OfflineBans/Commands/Modify.cs
> +            }
Тебе нужно проверить начиличе папки с банами только один раз, в методе `OnLoaded()`

2023-01-21 13:30 UTC, JasKill commented on src/Padoru.OfflineBans/Commands/Modify.cs
> +    public class Modify : ParentCommand
Ты должен наследоваться от интерфейса `ICommand`

2023-01-21 13:30 UTC, JasKill commented on src/Padoru.OfflineBans/Commands/Modify.cs
> +            File.WriteAllText(Tools.filepath + $"\\{id}.json", json);
Эти строки дублируются в команде `Add`. Тебе стоит сделать 2 метода в классе `WantedUser`. 
Один будет проверять время, другой добавлять.

2023-01-21 13:30 UTC, JasKill commented on src/Padoru.OfflineBans/Classes/WantedUser.cs
> +        public string Reason { get; set; }
Пустые строки между

2023-01-21 13:30 UTC, JasKill commented on src/Padoru.OfflineBans/Classes/WantedUser.cs
> +        public WantedUser() { }
Зачем нужен пустой конструктор?

2023-01-21 13:30 UTC, JasKill commented on src/Padoru.OfflineBans/Classes/WantedUser.cs
> +            r.Close();
Используй `File.ReadAllText()`

2023-01-21 13:30 UTC, JasKill commented on src/Padoru.OfflineBans/Classes/WantedUser.cs
> +﻿namespace Padoru.OffBans.Classes
Неправильный namespace

2023-01-21 13:30 UTC, JasKill commented on src/Padoru.OfflineBans/Classes/Tools.cs
> +            //}
Это уже тут не нужно?

2023-01-21 13:32 UTC, JasKill commented on src/Padoru.OfflineBans/Classes/Tools.cs
> +        public static string filepath { get; } = Paths.PluginAPI + dirname;
Используй метод `Path.Combine()`

2023-01-22 09:00 UTC, Skarpelen commented on src/Padoru.OfflineBans/Classes/WantedUser.cs
> +        public WantedUser() { }
Без него выдает следующую ошибку: System.InvalidOperationException: generated serializer for WantedUser does not support deserialize.

2023-01-22 13:35 UTC, JasKill requested changes
🐢

2023-01-22 13:35 UTC, JasKill commented on src/Padoru.OfflineBans/Loader.cs
> +            }
Перемести это в `Plugin.OnLoaded()`

2023-01-22 13:35 UTC, JasKill commented on src/Padoru.OfflineBans/Commands/Add.cs
> +            }
Сделай метод `bool Has(string userId)`, который будет проверять, ожидает ли игрок бана или нет

2023-01-22 13:35 UTC, JasKill commented on src/Padoru.OfflineBans/Commands/Delete.cs
> +            }
Используй метод(Has) выше, чтобы проверить наличие бана

2023-01-22 13:35 UTC, JasKill commented on src/Padoru.OfflineBans/Commands/Add.cs
> +            string reason = string.Join(" ", arguments.Skip(2).ToArray());
Есть ли смысл делать `ToArray()`?

2023-01-22 13:35 UTC, JasKill commented on src/Padoru.OfflineBans/Commands/Add.cs
> +            File.WriteAllText(Tools.FolderPath + $"\\{id}.json", json);
Сделай метод в WantedUser `Add(string userId, long time, string reason)` и используей его тут и в команде Modify

2023-01-22 13:35 UTC, JasKill commented on src/Padoru.OfflineBans/Classes/Tools.cs
> +                                             new Regex(@"/^\d{17}@steam\s.*/")};
Можешь объяснить, зачем 2 регулярного выражения?

2023-01-22 13:35 UTC, JasKill commented on src/Padoru.OfflineBans/Classes/Tools.cs
> +        public static string dirname { get; } = "Wanted";
`DirectoryName`

2023-01-22 15:23 UTC, Skarpelen commented on src/Padoru.OfflineBans/Classes/Tools.cs
> +                                             new Regex(@"/^\d{17}@steam\s.*/")};
Один для добавления и изменения, второй для удаления. Для удаления не обязательно вводить срок и причину, достаточно айдишника

2023-01-22 15:27 UTC, Skarpelen commented on src/Padoru.OfflineBans/Commands/Add.cs
> +            string reason = string.Join(" ", arguments.Skip(2).ToArray());
Похоже что нет, удалю

2023-01-22 16:36 UTC, JasKill commented on src/Padoru.OfflineBans/Classes/Tools.cs
> +                                             new Regex(@"/^\d{17}@steam\s.*/")};
Может сделаем по другому?
 - Сделаем 1 регулярное выражение для проверки правильности введённого userId.
 - В командах просто будет проверять количество аргуметов.

2023-01-22 18:37 UTC, Skarpelen commented on src/Padoru.OfflineBans/Classes/Tools.cs
> +                                             new Regex(@"/^\d{17}@steam\s.*/")};
Так и сделаю

2023-01-24 13:19 UTC, JasKill requested changes
Yes

2023-01-24 20:55 UTC, Skarpelen commented on src/Padoru.OfflineBan/Extensions/String.cs
> +        public static bool RelativeTimeToSeconds(this string time, out long seconds)
Оно теперь не воспринимает подобное: 1d5h. Такая функция больше не нужна?

2023-01-26 17:29 UTC, JasKill commented on src/Padoru.OfflineBan/Extensions/String.cs
> +        public static bool RelativeTimeToSeconds(this string time, out long seconds)
Добавил поддержку формата `1Y:6M`.
Если у тебя нету вопросов, я замержу этот пр.

2023-01-29 17:55 UTC, Skarpelen commented on src/Padoru.OfflineBan/Extensions/String.cs
> +        public static bool RelativeTimeToSeconds(this string time, out long seconds)
Вопросов нет

2023-01-30 13:31 UTC, JasKill approved these changes

2023-02-01 17:33 UTC, merged